<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <!--If you are willing to use platform-specific APIs, use conditional compilation.
    See https://docs.avaloniaui.net/docs/guides/platforms/platform-specific-code/dotnet for more details.-->
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
	<AssemblyName>Logshot.Desktop</AssemblyName>
	  <ApplicationIcon>..\Logshot\Assets\logshot-icon.ico</ApplicationIcon>

	  <!-- Versioning -->
	  <Version>1.0.0</Version>
	  <FileVersion>1.0.0.0</FileVersion>
	  <AssemblyVersion>1.0.0.0</AssemblyVersion>

	  <!-- Branding Metadata -->
	  <Title>Logshot</Title>
	  <Product>Logshot Desktop</Product>
	  <Authors>George Tsirogiannis</Authors>
	  <Company>George Tsirogiannis</Company>
	  <Copyright>Copyright © 2026 George Tsirogiannis</Copyright>
	  <Description>Daily shot-reporting application for script supervisors.</Description>
	  
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Supabase" />
	  <PackageReference Include="QuestPDF" />	  
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Tmds.DBus.Protocol" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Logshot\Logshot.csproj" />
  </ItemGroup>
</Project>
