<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
	<TargetOSPlatformVersion>34.0</TargetOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ApplicationId>com.georgetsirogiannis.Logshot</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
	<RuntimeIdentifiers>android-arm64;android-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <AndroidResource Include="Icon.png">
      <Link>Resources\drawable\Icon.png</Link>
    </AndroidResource>
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia.Android" />
		<PackageReference Include="Xamarin.AndroidX.Core.SplashScreen" />
		<PackageReference Include="Xamarin.AndroidX.Core" />
		<PackageReference Include="Xamarin.AndroidX.Core.Core.Ktx" ExcludeAssets="all" PrivateAssets="all" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Logshot\Logshot.csproj" />
  </ItemGroup>
</Project>
