<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  
  <ItemGroup>
    <AvaloniaXaml Remove=".vscode\**" />
    <Compile Remove=".vscode\**" />
    <EmbeddedResource Remove=".vscode\**" />
    <None Remove=".vscode\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="sqlite-net-pcl" />
    <PackageReference Include="Supabase" />
    <PackageReference Include="Tmds.DBus.Protocol" />
	<PackageReference Include="QuestPDF" />
  </ItemGroup>
</Project>
